In [1]:
import numpy as np

In [14]:
1. Write a Python Program to find sum of array?
a=np.random.randint(1,10,(3,4))
print("The array is:",a)
sum=0
for i in a:
    for j in i:
        sum= sum+j
print("the sum:-",sum)
         



The array is: [[8 5 4 5]
 [3 3 4 5]
 [4 7 3 6]]
the sum:- 57


In [20]:
#2. Write a Python Program to find largest element in an array?
ar=np.random.randint(1,10,(3,4))
print("The array is:",ar)
ar.max()

The array is: [[8 6 8 7]
 [2 2 2 7]
 [6 8 8 4]]


8

In [23]:
#3. Write a Python Program for array rotation?
ar=np.random.randint(1,50,(3,4))
print(ar)
ar.T

 


[[20  8 42 12]
 [ 6 13 11 33]
 [33 13 32 22]]


array([[20,  6, 33],
       [ 8, 13, 13],
       [42, 11, 32],
       [12, 33, 22]])

In [10]:
# 4.Write a Python Program to Split the array and add the first part to the end?
def splitArray(a, n, k): 
    for i in range(0, k): 
        x = a[0]
        for j in range(0, n-1):
            a[j] = a[j + 1]
          
        a[n-1] = x

In [15]:
a=[2,32,4,5,22,3,2,12]
n=len(a)
k=2
splitArray(a,n,k)

for i in range(0,n):
    print(a[i],end=" ")

4 5 22 3 2 12 2 32 

In [16]:
#5. Write a Python Program to check if given array is Monotonic?

def check_Monotonic(arr):
  
    return (all(arr[i] <= arr[i + 1] for i in range(len(arr) - 1)) or
            all(arr[i] >= arr[i + 1] for i in range(len(arr) - 1)))

In [18]:
arr=[6,7,8,9]
check_Monotonic(arr)

True