In [15]:
import numpy as np

In [8]:
#1. Write a Python Program to Add Two Matrices?

m1=np.random.randint(5,9,(3,3))
m2=np.random.randint(1,15,(3,3))
print(m1)
print(m2)
add=m1+m2
print("Addition of matrix is=")
print(add)

[[5 6 8]
 [8 6 7]
 [7 6 8]]
[[14 13  9]
 [13  3  5]
 [ 6  1  5]]
Addition of matrix is=
[[19 19 17]
 [21  9 12]
 [13  7 13]]


In [20]:
#2. Write a Python Program to Multiply Two Matrices?

m1=np.random.randint(1,10,(4,3))
m2=np.random.randint(5,9,(3,5))

multi=m1@m2
print("The multiplicartion of 2 matrix:")
print(multi)

The multiplicartion of 2 matrix:
[[ 71  92  88  82  91]
 [106 115 115 108 126]
 [ 73  60  60  66  77]
 [ 89  92  98  84 105]]


In [26]:
#3. Write a Python Program to Transpose a Matrix?

matrix=np.random.randint(3,10,(4,3))
print("The origional Matrix:")
print(matrix)

trans=matrix.T
print("The Transpose of matrix:")
print(trans)

The origional Matrix:
[[7 4 9]
 [6 6 6]
 [8 3 8]
 [7 7 7]]
The Transpose of matrix:
[[7 6 8 7]
 [4 6 3 7]
 [9 6 8 7]]


In [40]:
#4. Write a Python Program to Sort Words in Alphabetic Order?
string= "we love ineuron fsds course"
print("Origional string=",string)
l=string.split(" ")
l.sort()
s=" ".join(l)
print("The new sorted string=",s)
    
    

Origional string= we love ineuron fsds course
The new sorted string= course fsds ineuron love we


In [43]:
#5. Write a Python Program to Remove Punctuation From a String?

s="Hello!!!, I neuron ---is the best."
punc="''!()-[]{};:\,<>./?@#$%^&*_~''"
no_punc=""
for i in s:
    if i not in punc:
        no_punc=no_punc+i
print(no_punc)
        
   
        
        




Hello I neuron is the best
